apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: node-app
  type: NodePort
status:
  loadBalancer: {}